_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: none
  _partial_: none
  mode: none
  factor: none
  patience: none

net:
  _target_: none
  input_size: none
  lin1_size: none
  lin2_size: none
  lin3_size: none
  output_size: none

# compile model for faster training with pytorch 2.0
compile: false

# learning rate scheduler update interval: "epoch" or "step"
lr_interval: epoch